### ISSUE TITLE
Exercise 2: Task 3 - Getting issue while running notebook 02-Deploy Summarize Web service 

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Cognitive-services-and-deep-learning#48] opened 2021-06-28 12:21 UTC
Getting issue while running notebook 02-Deploy Summarize Web service.
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'gensim.summarization', please run print(service.get_logs()) to get details.",
  "details": [
    {
      "code": "CrashLoopBackOff",
      "message": "Error in entry script, ModuleNotFoundError: No module named 'gensim.summarization', please run print(service.get_logs()) to get details."
    }
  ]
}
Refer the below screenshot:
![image](https://user-images.githubusercontent.com/83394010/123635588-76097980-d839-11eb-90fb-c9363dd21d3c.png)

**Comment by shirolkar** [comment] 2021-06-29 14:39
@timahenning @DawnmarieDesJardins @Karthikkc123 
I am not able to reproduce the issue reported here. However, I ran into another issues deploying the model in notebook 2. I got an error that NLTK was unable to download the required data. I have fixed the issue I ran into. Please retest and let me know if you still run into an issue. Thanks. Jitendra

**Comment by DawnmarieDesJardins** [comment] 2021-07-03 00:33
No additional communication.  Closing issue as resolved with merge of PR #49

**Closed by DawnmarieDesJardins** 2021-07-03 00:33 UTC
